apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./deployment.yaml
  - ./deployment-public.yaml
  - ./virtual-services.yaml

commonLabels:
  section: backend
  num-virtual-services: "2"