apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dataware-tools-api-file-provider
spec:
  hosts:
    - "*"
  gateways:
    - dataware-tools-gateway
  http:
    - name: api-file-provider-public
      match:
        - uri:
            prefix: /api/latest/file_provider/download/
      rewrite:
        uri: /download/
      route:
        - destination:
            host: api-file-provider-public
      corsPolicy:
        allowHeaders:
          - Authorization
          - Content-Type
          - Content-Length
          - Content-Range
          - Accept-Ranges
          - ETag
          - Range
        allowMethods:
          - GET
          - HEAD
          - OPTIONS
        allowOrigins:
          - exact: 'https://webviz.io'
          - exact: 'https://webviz.hdwlab.com'
        exposeHeaders:
          - Authorization
          - Content-Type
          - Content-Length
          - Accept-Ranges
          - ETag
    - name: api-file-provider
      match:
        - uri:
            prefix: /api/latest/file_provider/
      rewrite:
        uri: /
      route:
        - destination:
            host: api-file-provider