apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-scene-viewer
    require-auth0-client-configs: disabled
  name: app-scene-viewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-scene-viewer
  strategy: {}
  template:
    metadata:
      labels:
        app: app-scene-viewer
        require-auth0: disabled
    spec:
      containers:
      - image: registry.gitlab.com/dataware-tools/app-scene-viewer:main
        name: app
        ports:
          - containerPort: 8080
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: app-scene-viewer
spec:
  selector:
    app: app-scene-viewer
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dataware-tools-app-scene-viewer
spec:
  hosts:
    - "*"
  gateways:
    - dataware-tools-gateway
  http:
    - match:
        - uri:
            prefix: /scene-viewer/
      rewrite:
        uri: /
      route:
        - destination:
            host: app-scene-viewer
