apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-launcher-next
    require-auth0-client-configs: enabled
  name: app-launcher-next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-launcher-next
  strategy: {}
  template:
    metadata:
      labels:
        app: app-launcher-next
        require-auth0: disabled
    spec:
      containers:
      - image: registry.gitlab.com/dataware-tools/app-launcher-next:v0.1.1
        name: app
        ports:
          - containerPort: 3000
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /launcher/healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: app-launcher-next
spec:
  selector:
    app: app-launcher-next
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dataware-tools-app-launcher-next
spec:
  hosts:
    - "*"
  gateways:
    - dataware-tools-gateway
  http:
    - match:
        - uri:
            prefix: /launcher
      route:
        - destination:
            host: app-launcher-next
