apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-job-store
    require-pydtk-v4: enabled
    require-webviz-config: enabled
  name: api-job-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-job-store
  strategy: {}
  template:
    metadata:
      labels:
        app: api-job-store
        version: v1
        require-auth0: enabled
        require-auth0-job-admin: enabled
    spec:
      containers:
      - image: registry.gitlab.com/dataware-tools/api-job-store:v2.0.1
        name: app
        ports:
          - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
          - name: SECRET_KEY
            value: "api-job-store"
          - name: WEBVIZ_URL
            value: '/scene-viewer/'
          - name: WEBSOCKET_SCHEME
            value: 'wss'
          - name: WEBSOCKET_HOST
            value: 'demo.dataware-tools.com'
          - name: WEBSOCKET_PORT
            value: '80'   # NOTE: Actual port is 443, but rosbridge causes an error with the actual value
        volumeMounts:
          - name: assets
            mountPath: /opt/app/api/assets
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
      imagePullSecrets:
        - name: regcred
      volumes:
        - name: assets
          configMap:
            name: api-job-store-assets
---
apiVersion: v1
kind: Service
metadata:
  name: api-job-store
spec:
  selector:
    app: api-job-store
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dataware-tools-api-job-store
spec:
  hosts:
    - "*"
  gateways:
    - dataware-tools-gateway
  http:
    #
    # APIs
    #
    - name: api-job-store
      match:
        - uri:
            prefix: /api/latest/job_store/
      rewrite:
        uri: /
      route:
        - destination:
            host: api-job-store