apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dataware-tools
spec:
  hosts:
    - $(dataware-tools-common-networking-gateway-host)
  gateways:
    - dataware-tools-gateway
  http:
    - match:
        - uri:
            exact: /
        - uri:
            prefix: /callback
      redirect:
        uri: /launcher
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dataware-tools-webviz
spec:
  hosts:
    - $(dataware-tools-common-networking-gateway-host)
  gateways:
    - dataware-tools-gateway
  http:
    - match:
        - uri:
            prefix: /ros-provider-test
      route:
        - destination:
            host: ros-provider-test