apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: app-data-browser-next
    section: frontend
  name: app-data-browser-next
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-data-browser-next
  strategy: {}
  template:
    metadata:
      labels:
        app: app-data-browser-next
        require-auth0: disabled
    spec:
      containers:
      - image: registry.gitlab.com/dataware-tools/app-data-browser-next:develop
        name: app
        ports:
          - containerPort: 3000
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /data-browser/healthz
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: app-data-browser-next
spec:
  selector:
    app: app-data-browser-next
  ports:
  - name: http
    protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: dataware-tools-app-data-browser
spec:
  hosts:
    - "*"
  gateways:
    - dataware-tools-gateway
  http:
    - match:
        - uri:
            prefix: /data-browser
      rewrite:
        uri: /data-browser
      route:
        - destination:
            host: app-data-browser-next