apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps
  - ../../common/networking
  - ../../common/security

patches:
  - path: ./auth0-client-configs.yaml
    target:
      kind: Deployment
      labelSelector: require-auth0-client-configs