apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../apps
  - ../../common/networking
  - ../../common/security
  - ../../contrib/webviz

patches:
  - path: ./pvc.yaml
    target:
      kind: PersistentVolumeClaim
      name: dataware-tools-uploaded-data

secretGenerator:
  - name: dataware-tools-apps
    behavior: replace
    envs:
      - envs/apps_secrets.env

configMapGenerator:
  - name: dataware-tools-apps
    behavior: replace
    envs:
      - envs/apps_configs.env
  - name: dataware-tools-common-networking
    behavior: replace
    envs:
      - envs/networking.env
  - name: dataware-tools-common-security
    behavior: replace
    envs:
      - envs/security.env
  - name: dataware-tools-contrib-webviz
    behavior: replace
    envs:
      - envs/webviz.env
