apiVersion: apps/v1
kind: Deployment
metadata:
  name: "*"
spec:
  template:
    spec:
      containers:
      - name: app
        volumeMounts:
          - mountPath: /opt/uploaded_data
            name: dataware-tools-uploaded-data
      volumes:
        - name: dataware-tools-uploaded-data
          persistentVolumeClaim:
            claimName: dataware-tools-uploaded-data