apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    require-pydtk-v4: enabled
  name: "*"
spec:
  template:
    spec:
      containers:
      - name: app
        env:
          - name: PYDTK_META_DB_ENGINE
            value: mongodb
          - name: PYDTK_META_DB_HOST
            value: mongodb:27017
          - name: PYDTK_META_DB_USERNAME
            value: demo
          - name: PYDTK_META_DB_PASSWORD
            value: demo
          - name: PYDTK_META_DB_DATABASE
            value: demo
