apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    require-auth0-client-secret: enabled
  name: "*"
spec:
  template:
    spec:
      containers:
        - name: app
          env:
            - name: AUTH0_DOMAIN
              value: $(dataware-tools-apps-auth0-domain)
            - name: AUTH0_CLIENT_ID
              value: $(dataware-tools-apps-auth0-client-id)
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth0
                  key: client-secret