apiVersion: apps/v1
kind: Deployment
metadata:
  name: "*"
spec:
  template:
    spec:
      containers:
      - name: app
        env:
          - name: WEBVIZ_URL
            value: $(dataware-tools-apps-webviz-app-url)
          - name: WEBSOCKET_HOST
            value: $(dataware-tools-apps-webviz-websocket-host)
